### ISSUE TITLE
Typo on "@import "~vue-mutiselect-boo....

### ISSUE THREAD

**Issue by fjd** [jgalindosl/vue-multiselect-bootstrap-theme#1]
Typo here: mutiselect instead of multiselect

`@import "~vue-mutiselect-bootstrap-theme/dist/vue-multiselect-bootstrap4.scss";`

https://www.npmjs.com/package/vue-**mutiselect**-bootstrap-theme
<img width="394" alt="Screenshot 2022-10-05" src="https://user-images.githubusercontent.com/111547/194028609-278412a7-dc06-4a6e-87f2-b5e15348a5e2.png">

**Comment by jgalindosl** [comment]
Thanks a lot!  Published a new npm registry without the typo.

[https://www.npmjs.com/package/vue-multiselect-bootstrap-theme](https://www.npmjs.com/package/vue-multiselect-bootstrap-theme)
